---
# yamllint disable rule:line-length
version: '3'

tasks:
  build-image:
    desc: Builds a docker image
    cmds:
      - docker build . -t danihodovic/celery-exporter

  trivy-scan:
    desc: Scans the docker image for vulnerabilities
    cmds:
      - trivy image --severity CRITICAL,HIGH --ignore-unfixed danihodovic/celery-exporter:latest
