{
 "title": "Celery / Tasks / By Task",
 "description": "A dashboard to monitor Celery tasks grouped by task name. The dashboards were generated using [celery-exporter](https://github.com/danihodovic/celery-exporter). Open issues and create feature requests in the repository.",
 "tags": [
  "celery",
  "celery-mixin"
 ],
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(celery_worker_up{}, cluster)"
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(celery_worker_up{cluster=\"$cluster\"}, namespace)"
   },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(celery_worker_up{cluster=\"$cluster\", namespace=\"$namespace\"}, job)"
   },
   {
    "name": "queue_name",
    "label": "Queue Name",
    "query": "label_values(celery_task_received_total{cluster=\"$cluster\", namespace=\"$namespace\", job=~\"$job\", queue_name!~\"None\"}, queue_name)"
   },
   {
    "name": "task",
    "label": "Task",
    "query": "label_values(celery_task_received_total{cluster=\"$cluster\", namespace=\"$namespace\", job=~\"$job\", queue_name=~\"$queue_name\", name!~\"None\"}, name)"
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Task Stats",
   "type": "table",
   "description": "A table of task statistics including success rate, succeeded, failed, sent, received, rejected, retried and revoked tasks grouped by task name.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (\n  round(\n    increase(\n      celery_task_succeeded_total{\n        cluster=\"$cluster\",\nnamespace=\"$namespace\",\njob=~\"$job\"\n,\nqueue_name=~\"$queue_name\"\n,\nname=~\"$task\",\nname!~\"None\"\n\n      }[$__range]\n    )\n  )\n) by (name)\n/(sum (\n  round(\n    increase(\n      celery_task_succeeded_total{\n        cluster=\"$cluster\",\nnamespace=\"$namespace\",\njob=~\"$job\"\n,\nqueue_name=~\"$queue_name\"\n,\nname=~\"$task\",\nname!~\"None\"\n\n      }[$__range]\n    )\n  )\n) by (name)\n+sum (\n  round(\n    increase(\n      celery_task_failed_total{\n        cluster=\"$cluster\",\nnamespace=\"$namespace\",\njob=~\"$job\"\n,\nqueue_name=~\"$queue_name\"\n,\nname=~\"$task\",\nname!~\"None\"\n\n      }[$__range]\n    )\n  )\n) by (name)\n) > -1\n"
    },
    {
     "expr": "sum (\n  round(\n    increase(\n      celery_task_succeeded_total{\n        cluster=\"$cluster\",\nnamespace=\"$namespace\",\njob=~\"$job\"\n,\nqueue_name=~\"$queue_name\"\n,\nname=~\"$task\",\nname!~\"None\"\n\n      }[$__range]\n    )\n  )\n) by (name) > 0\n"
    },
    {
     "expr": "sum (\n  round(\n    increase(\n      celery_task_failed_total{\n        cluster=\"$cluster\",\nnamespace=\"$namespace\",\njob=~\"$job\"\n,\nqueue_name=~\"$queue_name\"\n,\nname=~\"$task\",\nname!~\"None\"\n\n      }[$__range]\n    )\n  )\n) by (name) > 0\n"
    },
    {
     "expr": "sum (\n  round(\n    increase(\n      celery_task_sent_total{\n        cluster=\"$cluster\",\nnamespace=\"$namespace\",\njob=~\"$job\"\n,\nqueue_name=~\"$queue_name\"\n,\nname=~\"$task\",\nname!~\"None\"\n\n      }[$__range]\n    )\n  )\n) by (name) > 0\n"
    },
    {
     "expr": "sum (\n  round(\n    increase(\n      celery_task_received_total{\n        cluster=\"$cluster\",\nnamespace=\"$namespace\",\njob=~\"$job\"\n,\nqueue_name=~\"$queue_name\"\n,\nname=~\"$task\",\nname!~\"None\"\n\n      }[$__range]\n    )\n  )\n) by (name) > 0\n"
    },
    {
     "expr": "sum (\n  round(\n    increase(\n      celery_task_rejected_total{\n        cluster=\"$cluster\",\nnamespace=\"$namespace\",\njob=~\"$job\"\n,\nqueue_name=~\"$queue_name\"\n,\nname=~\"$task\",\nname!~\"None\"\n\n      }[$__range]\n    )\n  )\n) by (name) > 0\n"
    },
    {
     "expr": "sum (\n  round(\n    increase(\n      celery_task_retried_total{\n        cluster=\"$cluster\",\nnamespace=\"$namespace\",\njob=~\"$job\"\n,\nqueue_name=~\"$queue_name\"\n,\nname=~\"$task\",\nname!~\"None\"\n\n      }[$__range]\n    )\n  )\n) by (name) > 0\n"
    },
    {
     "expr": "sum (\n  round(\n    increase(\n      celery_task_revoked_total{\n        cluster=\"$cluster\",\nnamespace=\"$namespace\",\njob=~\"$job\"\n,\nqueue_name=~\"$queue_name\"\n,\nname=~\"$task\",\nname!~\"None\"\n\n      }[$__range]\n    )\n  )\n) by (name) > 0\n"
    }
   ]
  },
  {
   "title": "Task Exceptions",
   "type": "table",
   "description": "A table of task exceptions grouped by task name and exception type.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "round(\n  sum (\n    increase(\n      celery_task_failed_total{\n        cluster=\"$cluster\",\nnamespace=\"$namespace\",\njob=~\"$job\"\n,\nqueue_name=~\"$queue_name\"\n,\nname=~\"$task\",\nname!~\"None\"\n\n      }[$__range]\n    )\n  ) by (name, exception) > 0\n)\n"
    }
   ]
  },
  { "title": "Tasks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Tasks Completed",
   "type": "timeseries",
   "description": "A time series of tasks completed including succeeded, failed, sent, received, rejected, retried and revoked tasks grouped by task name.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (\n  round(\n    increase(\n      celery_task_succeeded_total{\n        cluster=\"$cluster\",\nnamespace=\"$namespace\",\njob=~\"$job\"\n,\nqueue_name=~\"$queue_name\"\n,\nname=~\"$task\",\nname!~\"None\"\n\n      }[$__rate_interval]\n    )\n  )\n) by (name) > 0\n",
     "legendFormat": "Succeeded - {{ name }}"
    },
    {
     "expr": "sum (\n  round(\n    increase(\n      celery_task_failed_total{\n        cluster=\"$cluster\",\nnamespace=\"$namespace\",\njob=~\"$job\"\n,\nqueue_name=~\"$queue_name\"\n,\nname=~\"$task\",\nname!~\"None\"\n\n      }[$__rate_interval]\n    )\n  )\n) by (name) > 0\n",
     "legendFormat": "Failed - {{ name }}"
    },
    {
     "expr": "sum (\n  round(\n    increase(\n      celery_task_sent_total{\n        cluster=\"$cluster\",\nnamespace=\"$namespace\",\njob=~\"$job\"\n,\nqueue_name=~\"$queue_name\"\n,\nname=~\"$task\",\nname!~\"None\"\n\n      }[$__rate_interval]\n    )\n  )\n) by (name) > 0\n",
     "legendFormat": "Sent - {{ name }}"
    },
    {
     "expr": "sum (\n  round(\n    increase(\n      celery_task_received_total{\n        cluster=\"$cluster\",\nnamespace=\"$namespace\",\njob=~\"$job\"\n,\nqueue_name=~\"$queue_name\"\n,\nname=~\"$task\",\nname!~\"None\"\n\n      }[$__rate_interval]\n    )\n  )\n) by (name) > 0\n",
     "legendFormat": "Received - {{ name }}"
    },
    {
     "expr": "sum (\n  round(\n    increase(\n      celery_task_retried_total{\n        cluster=\"$cluster\",\nnamespace=\"$namespace\",\njob=~\"$job\"\n,\nqueue_name=~\"$queue_name\"\n,\nname=~\"$task\",\nname!~\"None\"\n\n      }[$__rate_interval]\n    )\n  )\n) by (name) > 0\n",
     "legendFormat": "Retried - {{ name }}"
    },
    {
     "expr": "sum (\n  round(\n    increase(\n      celery_task_revoked_total{\n        cluster=\"$cluster\",\nnamespace=\"$namespace\",\njob=~\"$job\"\n,\nqueue_name=~\"$queue_name\"\n,\nname=~\"$task\",\nname!~\"None\"\n\n      }[$__rate_interval]\n    )\n  )\n) by (name) > 0\n",
     "legendFormat": "Revoked - {{ name }}"
    },
    {
     "expr": "sum (\n  round(\n    increase(\n      celery_task_rejected_total{\n        cluster=\"$cluster\",\nnamespace=\"$namespace\",\njob=~\"$job\"\n,\nqueue_name=~\"$queue_name\"\n,\nname=~\"$task\",\nname!~\"None\"\n\n      }[$__rate_interval]\n    )\n  )\n) by (name) > 0\n",
     "legendFormat": "Rejected - {{ name }}"
    }
   ]
  },
  {
   "title": "Task Exceptions",
   "type": "timeseries",
   "description": "A time series of task exceptions grouped by task name and exception type.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (\n  round(\n    increase(\n      celery_task_failed_total{\n        cluster=\"$cluster\",\nnamespace=\"$namespace\",\njob=~\"$job\"\n,\nqueue_name=~\"$queue_name\"\n,\nname=~\"$task\",\nname!~\"None\"\n\n      }[$__rate_interval]\n    )\n  )\n) by (name, exception) > 0\n",
     "legendFormat": "{{ name }}/{{ exception }}"
    }
   ]
  },
  {
   "title": "Tasks Runtime",
   "type": "timeseries",
   "description": "A time series of task runtime percentiles (P50, P95, P99) grouped by task name.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50,\n  sum(\n    irate(\n      celery_task_runtime_bucket{\n        cluster=\"$cluster\",\nnamespace=\"$namespace\",\njob=~\"$job\"\n,\nqueue_name=~\"$queue_name\"\n,\nname=~\"$task\",\nname!~\"None\"\n\n      }[$__rate_interval]\n    ) > 0\n  ) by (name, job, le)\n)\n",
     "legendFormat": "P50 - {{ name }}"
    },
    {
     "expr": "histogram_quantile(0.95,\n  sum(\n    irate(\n      celery_task_runtime_bucket{\n        cluster=\"$cluster\",\nnamespace=\"$namespace\",\njob=~\"$job\"\n,\nqueue_name=~\"$queue_name\"\n,\nname=~\"$task\",\nname!~\"None\"\n\n      }[$__rate_interval]\n    ) > 0\n  ) by (name, job, le)\n)\n",
     "legendFormat": "P95 - {{ name }}"
    },
    {
     "expr": "histogram_quantile(0.99,\n  sum(\n    irate(\n      celery_task_runtime_bucket{\n        cluster=\"$cluster\",\nnamespace=\"$namespace\",\njob=~\"$job\"\n,\nqueue_name=~\"$queue_name\"\n,\nname=~\"$task\",\nname!~\"None\"\n\n      }[$__rate_interval]\n    ) > 0\n  ) by (name, job, le)\n)\n",
     "legendFormat": "P99 - {{ name }}"
    }
   ]
  }
 ]
}