{
 "title": "Celery / Tasks / Overview",
 "description": "A dashboard that monitors Celery. The dashboards were generated using [celery-mixin](https://github.com/danihodovic/celery-exporter). Open issues and create feature requests in the repository.",
 "tags": [
  "celery",
  "celery-mixin"
 ],
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(celery_worker_up{}, cluster)"
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(celery_worker_up{cluster=\"$cluster\"}, namespace)"
   },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(celery_worker_up{cluster=\"$cluster\", namespace=\"$namespace\"}, job)"
   },
   {
    "name": "queue_name",
    "label": "Queue Name",
    "query": "label_values(celery_task_received_total{cluster=\"$cluster\", namespace=\"$namespace\", job=~\"$job\", name!~\"None\"}, queue_name)"
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Workers",
   "type": "stat",
   "description": "Number of active Celery Workers",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count(\n  celery_worker_up{\n    cluster=\"$cluster\",\nnamespace=\"$namespace\",\njob=~\"$job\"\n\n  } == 1\n)\n"
    }
   ]
  },
  {
   "title": "Workers Active Tasks",
   "type": "stat",
   "description": "Number of active tasks across all workers",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n  celery_worker_tasks_active{\n    cluster=\"$cluster\",\nnamespace=\"$namespace\",\njob=~\"$job\"\n\n  }\n)\n"
    }
   ]
  },
  {
   "title": "Tasks received by workers [1w]",
   "type": "stat",
   "description": "Number of tasks received by workers in the last week",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n  round(\n    increase(\n      celery_task_received_total{\n        cluster=\"$cluster\",\nnamespace=\"$namespace\",\njob=~\"$job\"\n,\nqueue_name=~\"$queue_name\",\n\n      }[1w]\n    )\n  )\n)\n"
    }
   ]
  },
  {
   "title": "Tasks Success Rate [1w]",
   "type": "stat",
   "description": "Rate of successful tasks in the last week",
   "gridPos": { "h": 4, "w": 5, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(\n  round(\n    increase(\n      celery_task_succeeded_total{\n        cluster=\"$cluster\",\nnamespace=\"$namespace\",\njob=~\"$job\"\n,\nqueue_name=~\"$queue_name\",\n\n      }[1w]\n    )\n  )\n)\n/(sum(\n  round(\n    increase(\n      celery_task_succeeded_total{\n        cluster=\"$cluster\",\nnamespace=\"$namespace\",\njob=~\"$job\"\n,\nqueue_name=~\"$queue_name\",\n\n      }[1w]\n    )\n  )\n)\n+sum(\n  round(\n    increase(\n      celery_task_failed_total{\n        cluster=\"$cluster\",\nnamespace=\"$namespace\",\njob=~\"$job\"\n,\nqueue_name=~\"$queue_name\",\n\n      }[1w]\n    )\n  )\n)\n)\n"
    }
   ]
  },
  {
   "title": "Average Runtime for Tasks [1w]",
   "type": "stat",
   "description": "Average runtime for tasks in the last week",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(\n  rate(\n    celery_task_runtime_sum{\n      cluster=\"$cluster\",\nnamespace=\"$namespace\",\njob=~\"$job\"\n,\nqueue_name=~\"$queue_name\",\n\n    }[1w]\n  )\n)\n/\nsum(\n  rate(\n    celery_task_runtime_count{\n      cluster=\"$cluster\",\nnamespace=\"$namespace\",\njob=~\"$job\"\n,\nqueue_name=~\"$queue_name\",\n\n    }[1w]\n  )\n) > 0\n"
    }
   ]
  },
  {
   "title": "Top Failed Tasks [1w]",
   "type": "table",
   "description": "Table of tasks with the most failures in the last week",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "round(\n  sum (\n    increase(\n      celery_task_failed_total{\n        cluster=\"$cluster\",\nnamespace=\"$namespace\",\njob=~\"$job\"\n,\nqueue_name=~\"$queue_name\",\n\n      }[1w]\n    ) > 0\n  )  by (job, name)\n)\n"
    }
   ]
  },
  {
   "title": "Top Task Exceptions [1w]",
   "type": "table",
   "description": "Table of the most common exceptions in the last week",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "round(\n  sum (\n    increase(\n      celery_task_failed_total{\n        cluster=\"$cluster\",\nnamespace=\"$namespace\",\njob=~\"$job\"\n,\nqueue_name=~\"$queue_name\",\n\n      }[1w]\n    )\n  ) by (job, exception) > 0\n)\n"
    }
   ]
  },
  {
   "title": "Top Average Task Runtime [1w]",
   "type": "table",
   "description": "Table of tasks with the highest average runtime in the last week",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum (\n  rate(\n    celery_task_runtime_sum{\n      cluster=\"$cluster\",\nnamespace=\"$namespace\",\njob=~\"$job\"\n,\nqueue_name=~\"$queue_name\",\n\n    }[1w]\n  )\n) by(name)\n/\nsum (\n  rate(\n    celery_task_runtime_count{\n      cluster=\"$cluster\",\nnamespace=\"$namespace\",\njob=~\"$job\"\n,\nqueue_name=~\"$queue_name\",\n\n    }[1w]\n  )\n) by (name) > 0\n"
    }
   ]
  },
  { "title": "Queues", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Queue Length",
   "type": "timeseries",
   "description": "Length of Celery queues",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (\n  celery_queue_length{\n    cluster=\"$cluster\",\nnamespace=\"$namespace\",\njob=~\"$job\"\n,\nqueue_name=~\"$queue_name\",\n\n  }\n) by (job, queue_name)\n",
     "legendFormat": "{{ job }}/{{ queue_name }}"
    }
   ]
  },
  { "title": "Tasks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Task Stats",
   "type": "table",
   "description": "Table with an overview of task statistics",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (\n  round(\n    increase(\n      celery_task_succeeded_total{\n        cluster=\"$cluster\",\nnamespace=\"$namespace\",\njob=~\"$job\"\n,\nqueue_name=~\"$queue_name\",\n\n      }[$__range]\n    )\n  )\n) by (job)\n/(sum (\n  round(\n    increase(\n      celery_task_succeeded_total{\n        cluster=\"$cluster\",\nnamespace=\"$namespace\",\njob=~\"$job\"\n,\nqueue_name=~\"$queue_name\",\n\n      }[$__range]\n    )\n  )\n) by (job)\n+sum (\n  round(\n    increase(\n      celery_task_failed_total{\n        cluster=\"$cluster\",\nnamespace=\"$namespace\",\njob=~\"$job\"\n,\nqueue_name=~\"$queue_name\",\n\n      }[$__range]\n    )\n  )\n) by (job)\n) > -1\n"
    },
    {
     "expr": "sum (\n  round(\n    increase(\n      celery_task_succeeded_total{\n        cluster=\"$cluster\",\nnamespace=\"$namespace\",\njob=~\"$job\"\n,\nqueue_name=~\"$queue_name\",\n\n      }[$__range]\n    )\n  )\n) by (job) > 0\n"
    },
    {
     "expr": "sum (\n  round(\n    increase(\n      celery_task_failed_total{\n        cluster=\"$cluster\",\nnamespace=\"$namespace\",\njob=~\"$job\"\n,\nqueue_name=~\"$queue_name\",\n\n      }[$__range]\n    )\n  )\n) by (job) > 0\n"
    },
    {
     "expr": "sum (\n  round(\n    increase(\n      celery_task_sent_total{\n        cluster=\"$cluster\",\nnamespace=\"$namespace\",\njob=~\"$job\"\n,\nqueue_name=~\"$queue_name\",\n\n      }[$__range]\n    )\n  )\n) by (job) > 0\n"
    },
    {
     "expr": "sum (\n  round(\n    increase(\n      celery_task_received_total{\n        cluster=\"$cluster\",\nnamespace=\"$namespace\",\njob=~\"$job\"\n,\nqueue_name=~\"$queue_name\",\n\n      }[$__range]\n    )\n  )\n) by (job) > 0\n"
    },
    {
     "expr": "sum (\n  round(\n    increase(\n      celery_task_rejected_total{\n        cluster=\"$cluster\",\nnamespace=\"$namespace\",\njob=~\"$job\"\n,\nqueue_name=~\"$queue_name\",\n\n      }[$__range]\n    )\n  )\n) by (job) > 0\n"
    },
    {
     "expr": "sum (\n  round(\n    increase(\n      celery_task_retried_total{\n        cluster=\"$cluster\",\nnamespace=\"$namespace\",\njob=~\"$job\"\n,\nqueue_name=~\"$queue_name\",\n\n      }[$__range]\n    )\n  )\n) by (job) > 0\n"
    },
    {
     "expr": "sum (\n  round(\n    increase(\n      celery_task_revoked_total{\n        cluster=\"$cluster\",\nnamespace=\"$namespace\",\njob=~\"$job\"\n,\nqueue_name=~\"$queue_name\",\n\n      }[$__range]\n    )\n  )\n) by (job) > 0\n"
    }
   ]
  },
  {
   "title": "Tasks Completed",
   "type": "timeseries",
   "description": "Number of tasks completed over time",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (\n  round(\n    increase(\n      celery_task_succeeded_total{\n        cluster=\"$cluster\",\nnamespace=\"$namespace\",\njob=~\"$job\"\n,\nqueue_name=~\"$queue_name\",\n\n      }[$__rate_interval]\n    )\n  )\n)\n",
     "legendFormat": "Succeeded"
    },
    {
     "expr": "sum (\n  round(\n    increase(\n      celery_task_failed_total{\n        cluster=\"$cluster\",\nnamespace=\"$namespace\",\njob=~\"$job\"\n,\nqueue_name=~\"$queue_name\",\n\n      }[$__rate_interval]\n    )\n  )\n)\n",
     "legendFormat": "Failed"
    },
    {
     "expr": "sum (\n  round(\n    increase(\n      celery_task_sent_total{\n        cluster=\"$cluster\",\nnamespace=\"$namespace\",\njob=~\"$job\"\n,\nqueue_name=~\"$queue_name\",\n\n      }[$__rate_interval]\n    )\n  )\n)\n",
     "legendFormat": "Sent"
    },
    {
     "expr": "sum (\n  round(\n    increase(\n      celery_task_received_total{\n        cluster=\"$cluster\",\nnamespace=\"$namespace\",\njob=~\"$job\"\n,\nqueue_name=~\"$queue_name\",\n\n      }[$__rate_interval]\n    )\n  )\n)\n",
     "legendFormat": "Received"
    },
    {
     "expr": "sum (\n  round(\n    increase(\n      celery_task_retried_total{\n        cluster=\"$cluster\",\nnamespace=\"$namespace\",\njob=~\"$job\"\n,\nqueue_name=~\"$queue_name\",\n\n      }[$__rate_interval]\n    )\n  )\n)\n",
     "legendFormat": "Retried"
    },
    {
     "expr": "sum (\n  round(\n    increase(\n      celery_task_revoked_total{\n        cluster=\"$cluster\",\nnamespace=\"$namespace\",\njob=~\"$job\"\n,\nqueue_name=~\"$queue_name\",\n\n      }[$__rate_interval]\n    )\n  )\n)\n",
     "legendFormat": "Revoked"
    },
    {
     "expr": "sum (\n  round(\n    increase(\n      celery_task_rejected_total{\n        cluster=\"$cluster\",\nnamespace=\"$namespace\",\njob=~\"$job\"\n,\nqueue_name=~\"$queue_name\",\n\n      }[$__rate_interval]\n    )\n  )\n)\n",
     "legendFormat": "Rejected"
    }
   ]
  },
  {
   "title": "Tasks Runtime",
   "type": "timeseries",
   "description": "Task runtime percentiles over time",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50,\n  sum(\n    irate(\n      celery_task_runtime_bucket{\n        cluster=\"$cluster\",\nnamespace=\"$namespace\",\njob=~\"$job\"\n,\nqueue_name=~\"$queue_name\",\n\n      }[$__rate_interval]\n    ) > 0\n  ) by (job, le)\n)\n",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.95,\n  sum(\n    irate(\n      celery_task_runtime_bucket{\n        cluster=\"$cluster\",\nnamespace=\"$namespace\",\njob=~\"$job\"\n,\nqueue_name=~\"$queue_name\",\n\n      }[$__rate_interval]\n    ) > 0\n  ) by (job, le)\n)\n",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99,\n  sum(\n    irate(\n      celery_task_runtime_bucket{\n        cluster=\"$cluster\",\nnamespace=\"$namespace\",\njob=~\"$job\"\n,\nqueue_name=~\"$queue_name\",\n\n      }[$__rate_interval]\n    ) > 0\n  ) by (job, le)\n)\n",
     "legendFormat": "P99"
    }
   ]
  }
 ]
}